#!/usr/bin/env python3
"""Diagnostic report for the Tier-1 (meteostat) cascade.

For every row in ``data/raw/event_geo.csv`` this script calls
``resolve_for_anomaly`` (the unified resolver that returns one station
serving both event-day and baseline-window queries) and dumps the
result to ``reports/tier1_validation.md`` plus an accompanying CSV.

The hand-curated ``day_temp_C`` column from the source CSV is included
as a cross-reference, *not* as a validation target — those values were
qualitative sanity checks from secondary sources and the analysis
itself only uses ``event_day - baseline_mean`` computed from the same
meteostat station, so absolute disagreement with the manual value is
expected and unimportant.

Run from the repo root:

    python scripts/validate_tier1.py
"""

from __future__ import annotations

import warnings
from pathlib import Path

import pandas as pd

from thermostrife.constants import CURATED_CSV, EVENT_GEO_CSV, REPORTS_DIR
from thermostrife.sources.meteostat_src import resolve_for_anomaly

REPORT_PATH = REPORTS_DIR / "tier1_validation.md"


def run() -> pd.DataFrame:
    """Resolve every row in event_geo.csv via Tier 1 and return the frame."""
    warnings.filterwarnings("ignore")
    curated = pd.read_csv(CURATED_CSV).set_index("event_id")
    geo = pd.read_csv(EVENT_GEO_CSV).set_index("event_id")
    rows = []
    for event_id, grow in geo.iterrows():
        crow = curated.loc[event_id]
        when = pd.to_datetime(crow["start_date"]).date()
        r = resolve_for_anomaly(grow["lat"], grow["lon"], when, radius_km=60)
        baseline_mean = float(r.baseline["tmax"].mean()) if len(r.baseline) else None
        baseline_std = (
            float(r.baseline["tmax"].std(ddof=1)) if len(r.baseline) > 1 else None
        )
        anomaly = (
            r.tmax_event_c - baseline_mean
            if (r.tmax_event_c is not None and baseline_mean is not None)
            else None
        )
        rows.append(
            {
                "event_id": event_id,
                "date": when.isoformat(),
                "manual_C": float(crow["day_temp_C"])
                if pd.notna(crow["day_temp_C"])
                else None,
                "tier1_C": r.tmax_event_c,
                "baseline_mean_C": baseline_mean,
                "baseline_std_C": baseline_std,
                "baseline_n": len(r.baseline) if len(r.baseline) else None,
                "anomaly_C": anomaly,
                "station": r.station_id or None,
                "note": r.note,
            }
        )
    return pd.DataFrame(rows)


def write_report(df: pd.DataFrame, out: Path = REPORT_PATH) -> None:
    out.parent.mkdir(parents=True, exist_ok=True)
    n_total = len(df)
    n_resolved = df["tier1_C"].notna().sum()
    n_with_baseline = df["baseline_n"].notna().sum()

    with out.open("w") as f:
        f.write("# Tier-1 (meteostat) diagnostic report\n\n")
        f.write(
            "Generated by `scripts/validate_tier1.py`. For each event_geo row "
            "this calls `resolve_for_anomaly`, which commits to a single "
            "meteostat station serving both the event-day fetch and the "
            "±5-year same-month baseline window — so the anomaly column "
            "below is an apples-to-apples internal computation, not a "
            "comparison with the hand-curated `manual_C` value.\n\n"
        )
        f.write("## Coverage\n\n")
        f.write(f"- Rows in `event_geo.csv`: **{n_total}**\n")
        f.write(f"- Resolved at Tier 1: **{n_resolved} / {n_total}**\n")
        f.write(f"- With baseline window: **{n_with_baseline} / {n_total}**\n\n")
        f.write(
            "Misses are expected for pre-1920 events (Paris 1871, Chicago "
            "1919, LAX 1965) — meteostat coverage thins out and these rows "
            "are the motivation for Tier 2 (long-record observatories) and "
            "Tier 4 (20CRv3 reanalysis).\n\n"
        )

        f.write("## Per-row results\n\n")
        f.write(
            "| event_id | date | manual* | Tier 1 | baseline mean | baseline n "
            "| anomaly | station | note |\n"
        )
        f.write(
            "|----------|------|--------:|-------:|--------------:|----------:"
            "|--------:|---------|------|\n"
        )
        for _, r in df.iterrows():
            man = f"{r['manual_C']:.1f}" if pd.notna(r["manual_C"]) else "—"
            t1 = f"{r['tier1_C']:.1f}" if pd.notna(r["tier1_C"]) else "—"
            bm = f"{r['baseline_mean_C']:.2f}" if pd.notna(r["baseline_mean_C"]) else "—"
            bn = f"{int(r['baseline_n'])}" if pd.notna(r["baseline_n"]) else "—"
            anom = f"{r['anomaly_C']:+.2f}" if pd.notna(r["anomaly_C"]) else "—"
            station = r["station"] if pd.notna(r["station"]) else "—"
            f.write(
                f"| `{r['event_id']}` | {r['date']} | {man} | {t1} | {bm} "
                f"| {bn} | {anom} | `{station}` | {r['note']} |\n"
            )

        f.write(
            "\n*`manual_C`* is the hand-curated value from the source CSV, "
            "shown for cross-reference only. The analysis uses `anomaly` "
            "(internally consistent: event-day minus same-station "
            "same-month baseline).\n"
        )


def main() -> int:
    df = run()
    REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    df.to_csv(REPORTS_DIR / "tier1_validation.csv", index=False)
    write_report(df)
    print(f"[done] {REPORT_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
