#!/usr/bin/env python3
"""Diagnostic report for the full tiered weather-archive cascade.

For every row in ``data/raw/event_geo.csv`` this script calls
``thermostrife.lookup.resolve_event_anomaly``, which walks Tiers 1-4
in order (meteostat → HadCET → ERA5 stub → 20CRv3 stub) until one
returns a (event_day, baseline_window) pair sourced from a single
underlying series.

The hand-curated ``day_temp_C`` column is shown for cross-reference
only; the analysis uses ``anomaly = event - baseline`` computed
internally, never the manual value.

Run from the repo root:

    python scripts/validate_cascade.py

Writes ``reports/cascade_validation.{md,csv}``.
"""

from __future__ import annotations

import warnings
from collections import Counter
from pathlib import Path

import pandas as pd

from thermostrife.constants import CURATED_CSV, EVENT_GEO_CSV, REPORTS_DIR
from thermostrife.lookup import resolve_event_anomaly

REPORT_PATH = REPORTS_DIR / "cascade_validation.md"


def run() -> pd.DataFrame:
    warnings.filterwarnings("ignore")
    curated = pd.read_csv(CURATED_CSV).set_index("event_id")
    geo = pd.read_csv(EVENT_GEO_CSV).set_index("event_id")
    rows = []
    for event_id, grow in geo.iterrows():
        crow = curated.loc[event_id]
        when = pd.to_datetime(crow["start_date"]).date()
        r = resolve_event_anomaly(grow["lat"], grow["lon"], when, radius_km=60)
        baseline_mean = float(r.baseline["tmax"].mean()) if len(r.baseline) else None
        baseline_std = (
            float(r.baseline["tmax"].std(ddof=1)) if len(r.baseline) > 1 else None
        )
        anomaly = (
            r.tmax_event_c - baseline_mean
            if (r.tmax_event_c is not None and baseline_mean is not None)
            else None
        )
        rows.append(
            {
                "event_id": event_id,
                "date": when.isoformat(),
                "manual_C": float(crow["day_temp_C"])
                if pd.notna(crow["day_temp_C"])
                else None,
                "event_C": r.tmax_event_c,
                "baseline_mean_C": baseline_mean,
                "baseline_std_C": baseline_std,
                "baseline_n": len(r.baseline) if len(r.baseline) else None,
                "anomaly_C": anomaly,
                "station": r.station_id or None,
                "provenance": r.provenance,
                "note": r.note,
            }
        )
    return pd.DataFrame(rows)


def write_report(df: pd.DataFrame, out: Path = REPORT_PATH) -> None:
    out.parent.mkdir(parents=True, exist_ok=True)
    n_total = len(df)
    resolved = df.dropna(subset=["event_C"])
    by_tier = Counter(resolved["provenance"])

    with out.open("w") as f:
        f.write("# Cascade validation report\n\n")
        f.write(
            "Generated by `scripts/validate_cascade.py`. Each row was "
            "resolved by `thermostrife.lookup.resolve_event_anomaly`, "
            "which walks Tiers 1-4 in order and commits to whichever tier "
            "first returns a single-source (event_day, baseline_window) "
            "pair.\n\n"
        )
        f.write("## Coverage\n\n")
        f.write(f"- Rows in `event_geo.csv`: **{n_total}**\n")
        f.write(f"- Resolved: **{len(resolved)} / {n_total}**\n")
        for tier_name in sorted(by_tier):
            f.write(f"  - `{tier_name}`: **{by_tier[tier_name]}**\n")
        f.write("\n")

        f.write("## Anomaly summary (resolved rows)\n\n")
        if not resolved.empty:
            anom = resolved["anomaly_C"]
            f.write(f"- Mean anomaly: **{anom.mean():+.2f} °C**\n")
            f.write(f"- Median anomaly: **{anom.median():+.2f} °C**\n")
            f.write(f"- Positive anomalies: **{(anom > 0).sum()}**\n")
            f.write(f"- Negative anomalies: **{(anom < 0).sum()}**\n\n")

        f.write("## Per-row results\n\n")
        f.write(
            "| event_id | date | manual* | event | baseline | n | anomaly | "
            "station | provenance |\n"
        )
        f.write(
            "|----------|------|--------:|------:|---------:|--:|--------:|"
            "---------|------------|\n"
        )
        for _, r in df.iterrows():
            man = f"{r['manual_C']:.1f}" if pd.notna(r["manual_C"]) else "—"
            ev = f"{r['event_C']:.1f}" if pd.notna(r["event_C"]) else "—"
            bm = f"{r['baseline_mean_C']:.2f}" if pd.notna(r["baseline_mean_C"]) else "—"
            bn = f"{int(r['baseline_n'])}" if pd.notna(r["baseline_n"]) else "—"
            an = f"{r['anomaly_C']:+.2f}" if pd.notna(r["anomaly_C"]) else "—"
            st = r["station"] if pd.notna(r["station"]) else "—"
            prov = r["provenance"] if pd.notna(r["provenance"]) else "—"
            f.write(
                f"| `{r['event_id']}` | {r['date']} | {man} | {ev} | {bm} "
                f"| {bn} | {an} | `{st}` | `{prov}` |\n"
            )
        f.write(
            "\n*`manual_C`* is the hand-curated value from the source CSV, "
            "shown for cross-reference only.\n"
        )


def main() -> int:
    df = run()
    REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    df.to_csv(REPORTS_DIR / "cascade_validation.csv", index=False)
    write_report(df)
    print(f"[done] {REPORT_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
